"""The compliance and procurement report.

Everything else in Racik is a screen. This is the document: one printable page
an SPPG hands to a supervisor, an auditor, or the BGN — showing what will be
served, whether it meets AKG, what it costs, and what to buy.

It is deliberately a single self-contained HTML file with print styles rather
than a generated PDF: no extra dependency, it prints to PDF from any browser,
and it stays readable if someone opens the file in five years.

The report states its own limits. A compliance document that hides a relaxed
nutrient floor, or presents an unverified micronutrient as if it were enforced,
is worse than no document — so relaxations get their own section and advisory
nutrients are marked in every table they appear in.
"""
from __future__ import annotations

import html
from datetime import date
from typing import Iterable, Optional

from .akg import BINDING_NUTRIENTS, NUTRIENT_META
from .config import MBG, SLOT_LABELS_EN, SLOT_LABELS_ID, SLOTS
from .i18n import norm_lang, t, unit
from .optimizer import PlanResult
from .procurement import ProcurementLine, totals

# Report-only wording. Kept here rather than in i18n.py because it is document
# furniture, not application prose.
STRINGS = {
    "id": {
        "title": "Laporan Kepatuhan & Kebutuhan Bahan",
        "subtitle": "Program Makan Bergizi Gratis",
        "generated": "Dibuat", "stage": "Jenjang", "days": "Jumlah hari",
        "portions": "Porsi per hari", "region": "Preferensi daerah",
        "budget": "Pagu bahan / porsi", "none": "Tanpa preferensi",
        "s_summary": "Ringkasan", "s_menu": "Menu harian",
        "s_compliance": "Kepatuhan gizi", "s_relax": "Batas yang dilonggarkan",
        "s_proc": "Kebutuhan bahan", "s_notes": "Catatan & keterbatasan",
        "mean_cost": "Biaya bahan rata-rata / porsi",
        "mean_adequacy": "Pemenuhan AKG rata-rata",
        "total_cost": "Total biaya bahan",
        "relaxed": "Batas gizi dilonggarkan",
        "day": "Hari", "slot": "Komponen", "dish": "Hidangan",
        "province": "Asal", "cost": "Biaya", "energy": "Energi",
        "protein": "Protein", "nutrient": "Zat gizi", "value": "Tercapai",
        "target": "Target", "pct": "%", "short": "Kurang",
        "ingredient": "Bahan", "weight": "Berat kotor", "used_in": "Dipakai pada",
        "items": "bahan", "advisory": "INFO",
        "advisory_note": ("Baris bertanda INFO bersifat informasi saja: nilai "
                          "mikronutrien AKG 2019 berbeda antar sumber sekunder "
                          "dan belum dijadikan batasan optimasi."),
        "relax_none": "Semua batas bawah gizi terpenuhi tanpa pelonggaran.",
        "sign_prepared": "Disusun oleh", "sign_approved": "Disetujui oleh",
        "footer": ("Angka gizi dari TKPI 2020 (basis berat mentah, disesuaikan "
                   "BDD dan faktor retensi FAO/INFOODS). Biaya dihitung atas "
                   "berat kotor. Dihasilkan oleh Racik."),
    },
    "en": {
        "title": "Compliance & Procurement Report",
        "subtitle": "Makan Bergizi Gratis programme",
        "generated": "Generated", "stage": "Stage", "days": "Days",
        "portions": "Portions per day", "region": "Regional preference",
        "budget": "Ingredient budget / portion", "none": "No preference",
        "s_summary": "Summary", "s_menu": "Daily menu",
        "s_compliance": "Nutrient compliance", "s_relax": "Relaxed floors",
        "s_proc": "Ingredient requirements", "s_notes": "Notes & limitations",
        "mean_cost": "Mean ingredient cost / portion",
        "mean_adequacy": "Mean AKG adequacy",
        "total_cost": "Total ingredient cost",
        "relaxed": "Nutrient floors relaxed",
        "day": "Day", "slot": "Component", "dish": "Dish",
        "province": "Origin", "cost": "Cost", "energy": "Energy",
        "protein": "Protein", "nutrient": "Nutrient", "value": "Achieved",
        "target": "Target", "pct": "%", "short": "Short by",
        "ingredient": "Ingredient", "weight": "Gross weight",
        "used_in": "Used in", "items": "ingredients", "advisory": "INFO",
        "advisory_note": ("Rows marked INFO are informational only: AKG 2019 "
                          "micronutrient values disagree across secondary "
                          "sources and are not enforced as constraints."),
        "relax_none": "Every nutrient floor was met without relaxation.",
        "sign_prepared": "Prepared by", "sign_approved": "Approved by",
        "footer": ("Nutrient values from TKPI 2020 (raw-weight basis, adjusted "
                   "for BDD and FAO/INFOODS retention factors). Cost charged on "
                   "gross weight. Generated by Racik."),
    },
}

_CSS = """
:root{--ink:#1F2B22;--soft:#4A5A4C;--line:#DCD4BC;--leaf:#3F6B4F;
      --gold:#E8A33D;--wash:#FDF6BA;--chili:#C0392B;--paper:#fff}
*{box-sizing:border-box}
body{margin:0;background:#F7F3E8;color:var(--ink);font-size:11pt;line-height:1.5;
     font-family:'Helvetica Neue',Arial,sans-serif}
.sheet{max-width:210mm;margin:0 auto;background:var(--paper);padding:16mm 14mm}
h1{font-size:20pt;margin:0}
h2{font-size:13pt;margin:22px 0 8px;padding-bottom:5px;
   border-bottom:1.5px solid var(--ink)}
.sub{color:var(--soft);font-size:10pt;margin:3px 0 0}
.meta{display:grid;grid-template-columns:repeat(3,1fr);gap:1px;background:var(--line);
      border:1px solid var(--line);margin-top:14px}
.meta div{background:var(--paper);padding:7px 9px}
.meta b{display:block;font-size:8pt;text-transform:uppercase;letter-spacing:.07em;
        color:var(--soft);font-weight:700}
.meta span{font-size:11pt}
.kpis{display:grid;grid-template-columns:repeat(4,1fr);gap:8px;margin-top:12px}
.kpi{border:1.5px solid var(--ink);padding:9px 11px}
.kpi b{display:block;font-size:8pt;text-transform:uppercase;letter-spacing:.06em;
       color:var(--soft)}
.kpi span{font-size:15pt;font-weight:700}
table{width:100%;border-collapse:collapse;font-size:9.5pt;margin-top:8px}
th{text-align:left;background:#EFE9D8;border-bottom:1.5px solid var(--line);
   padding:5px 7px;font-size:8pt;text-transform:uppercase;letter-spacing:.05em}
td{padding:5px 7px;border-bottom:1px solid #EFE9D8;vertical-align:top}
td.n,th.n{text-align:right;font-variant-numeric:tabular-nums;white-space:nowrap}
tr.day td{background:#F7F3E8;font-weight:700}
.tag{font-size:7.5pt;font-weight:700;border:1px solid var(--gold);background:#FFF8EA;
     padding:0 4px;color:#6B4E14}
.bar{height:6px;background:#EFE9D8;min-width:60px}
.bar i{display:block;height:100%;background:var(--leaf)}
.bar i.short{background:var(--gold)}.bar i.bad{background:var(--chili)}
.note{background:var(--wash);border:1px solid var(--gold);padding:9px 11px;
      font-size:9pt;margin-top:10px}
.warn{border-left:3px solid var(--chili);background:#F6DCD8;padding:8px 11px;
      font-size:9.5pt;margin-top:8px}
ul{margin:6px 0;padding-left:17px;font-size:9pt;color:var(--soft)}
li{margin-bottom:4px}
.sign{display:grid;grid-template-columns:1fr 1fr;gap:30px;margin-top:26px}
.sign div{border-top:1px solid var(--ink);padding-top:5px;font-size:9pt;
          color:var(--soft);margin-top:44px}
.foot{margin-top:20px;padding-top:9px;border-top:1px solid var(--line);
      font-size:8pt;color:var(--soft)}
@media print{
  body{background:#fff}
  .sheet{max-width:none;padding:0}
  h2{break-after:avoid}
  table{break-inside:auto}
  tr{break-inside:avoid}
  @page{margin:14mm}
}
"""


def _rp(value: float, lang: str) -> str:
    sep = "." if lang == "id" else ","
    return "Rp" + f"{round(value):,}".replace(",", sep)


def _e(value) -> str:
    return html.escape(str(value if value is not None else ""))


def build_report(result: PlanResult, procurement: Iterable[ProcurementLine],
                 lang: str = "id", sppg_name: str = "") -> str:
    """Render the printable compliance + procurement document."""
    lang = norm_lang(lang)
    s = STRINGS[lang]
    slot_labels = SLOT_LABELS_ID if lang == "id" else SLOT_LABELS_EN
    label_idx = 0 if lang == "id" else 1
    request = result.request
    portions = request.portions
    lines = list(procurement)
    proc_totals = totals(lines)
    summary = result.summary()

    day_names = (["Senin", "Selasa", "Rabu", "Kamis", "Jumat", "Sabtu", "Minggu"]
                 if lang == "id" else
                 ["Monday", "Tuesday", "Wednesday", "Thursday", "Friday",
                  "Saturday", "Sunday"])

    # ---------------------------------------------------------- menu table
    menu_rows = []
    for day in result.days:
        menu_rows.append(
            f'<tr class="day"><td colspan="5">{_e(day_names[day.day_index % 7])}'
            f' &mdash; {_rp(day.cost_per_portion_idr, lang)}/{"porsi" if lang=="id" else "portion"}'
            f' &middot; {day.nutrients["energy_kcal"]:.0f} {unit(lang, "kkal")}'
            f' &middot; AKG {result.adequacy(day) * 100:.0f}%</td></tr>')
        for slot in SLOTS:
            dish = day.dishes[slot]
            if dish is None:
                continue
            menu_rows.append(
                f"<tr><td>{_e(slot_labels[slot])}</td>"
                f"<td>{_e(dish.name)}</td><td>{_e(dish.province)}</td>"
                f'<td class="n">{dish.per_portion.get("energy_kcal", 0):.0f}</td>'
                f'<td class="n">{_rp(dish.cost_per_portion_idr, lang)}</td></tr>')

    # ---------------------------------------------------------- compliance
    compliance_rows = []
    for day in result.days:
        compliance_rows.append(
            f'<tr class="day"><td colspan="5">{_e(day_names[day.day_index % 7])}</td></tr>')
        for key, meta in NUTRIENT_META.items():
            target = result.targets.get(key)
            if not target:
                continue
            value = day.nutrients.get(key, 0.0)
            pct = value / target * 100
            binding = key in BINDING_NUTRIENTS
            cls = "" if pct >= 95 else "short" if pct >= 80 else "bad"
            tag = "" if binding else f' <span class="tag">{s["advisory"]}</span>'
            compliance_rows.append(
                f"<tr><td>{_e(meta[label_idx])}{tag}</td>"
                f'<td class="n">{value:.1f}</td>'
                f'<td class="n">{target:.1f} {_e(unit(lang, meta[2]))}</td>'
                f'<td class="n">{pct:.0f}%</td>'
                f'<td><div class="bar"><i class="{cls}" '
                f'style="width:{min(100, pct):.0f}%"></i></div></td></tr>')

    # ---------------------------------------------------------- relaxations
    if result.relaxations:
        relax_rows = "".join(
            f"<tr><td>{_e(day_names[r.day_index % 7])}</td>"
            f"<td>{_e(NUTRIENT_META[r.nutrient][label_idx])}</td>"
            f'<td class="n">{r.shortfall:.1f}</td>'
            f'<td class="n">{r.target:.1f} {_e(unit(lang, NUTRIENT_META[r.nutrient][2]))}</td>'
            f'<td class="n">-{r.share * 100:.0f}%</td></tr>'
            for r in result.relaxations)
        relax_block = (
            f'<div class="warn">{len(result.relaxations)} '
            f'{_e(s["relaxed"]).lower()}.</div>'
            f"<table><thead><tr><th>{_e(s['day'])}</th><th>{_e(s['nutrient'])}</th>"
            f"<th class='n'>{_e(s['short'])}</th><th class='n'>{_e(s['target'])}</th>"
            f"<th class='n'>{_e(s['pct'])}</th></tr></thead>"
            f"<tbody>{relax_rows}</tbody></table>")
    else:
        relax_block = f'<div class="note">{_e(s["relax_none"])}</div>'

    # ---------------------------------------------------------- procurement
    proc_rows = "".join(
        f"<tr><td>{_e(line.name)}</td>"
        f'<td class="n">{line.gross_kg:.2f} kg</td>'
        f'<td class="n">{_rp(line.cost_idr, lang)}</td>'
        f'<td style="font-size:8pt;color:#4A5A4C">'
        f'{_e(", ".join(sorted(line.used_in)[:2]))}</td></tr>'
        for line in lines)

    notes = "".join(f"<li>{_e(n)}</li>" for n in _notes_for(result, lang))
    region = request.province or s["none"]
    total_cost = result.mean_cost_per_portion * portions * len(result.days)

    return f"""<!DOCTYPE html>
<html lang="{lang}"><head><meta charset="utf-8">
<title>{_e(s['title'])} — Racik</title><style>{_CSS}</style></head>
<body><div class="sheet">

  <h1>{_e(s['title'])}</h1>
  <p class="sub">{_e(s['subtitle'])}{f" &middot; {_e(sppg_name)}" if sppg_name else ""}</p>

  <div class="meta">
    <div><b>{_e(s['generated'])}</b><span>{date.today().isoformat()}</span></div>
    <div><b>{_e(s['stage'])}</b><span>{_e(result.band.label_id if lang == 'id' else result.band.label_en)}</span></div>
    <div><b>{_e(s['days'])}</b><span>{len(result.days)}</span></div>
    <div><b>{_e(s['portions'])}</b><span>{portions:,}</span></div>
    <div><b>{_e(s['region'])}</b><span>{_e(region)}</span></div>
    <div><b>{_e(s['budget'])}</b><span>{_rp(request.config.ingredient_budget_idr, lang)}</span></div>
  </div>

  <h2>{_e(s['s_summary'])}</h2>
  <div class="kpis">
    <div class="kpi"><b>{_e(s['mean_cost'])}</b><span>{_rp(summary['mean_cost_per_portion_idr'], lang)}</span></div>
    <div class="kpi"><b>{_e(s['mean_adequacy'])}</b><span>{summary['mean_adequacy'] * 100:.0f}%</span></div>
    <div class="kpi"><b>{_e(s['total_cost'])}</b><span>{_rp(total_cost, lang)}</span></div>
    <div class="kpi"><b>{_e(s['relaxed'])}</b><span>{summary['relaxed_floors']}</span></div>
  </div>

  <h2>{_e(s['s_menu'])}</h2>
  <table><thead><tr><th>{_e(s['slot'])}</th><th>{_e(s['dish'])}</th>
    <th>{_e(s['province'])}</th><th class="n">{_e(s['energy'])}</th>
    <th class="n">{_e(s['cost'])}</th></tr></thead>
    <tbody>{''.join(menu_rows)}</tbody></table>

  <h2>{_e(s['s_compliance'])}</h2>
  <table><thead><tr><th>{_e(s['nutrient'])}</th><th class="n">{_e(s['value'])}</th>
    <th class="n">{_e(s['target'])}</th><th class="n">{_e(s['pct'])}</th>
    <th></th></tr></thead>
    <tbody>{''.join(compliance_rows)}</tbody></table>
  <div class="note">{_e(s['advisory_note'])}</div>

  <h2>{_e(s['s_relax'])}</h2>
  {relax_block}

  <h2>{_e(s['s_proc'])}</h2>
  <p class="sub">{proc_totals['items']} {_e(s['items'])} &middot;
     {proc_totals['total_mass_kg']:,.1f} kg &middot;
     {_rp(proc_totals['total_cost_idr'], lang)}</p>
  <table><thead><tr><th>{_e(s['ingredient'])}</th>
    <th class="n">{_e(s['weight'])}</th><th class="n">{_e(s['cost'])}</th>
    <th>{_e(s['used_in'])}</th></tr></thead>
    <tbody>{proc_rows}</tbody></table>

  <h2>{_e(s['s_notes'])}</h2>
  <ul>{notes}</ul>

  <div class="sign">
    <div>{_e(s['sign_prepared'])}</div>
    <div>{_e(s['sign_approved'])}</div>
  </div>

  <p class="foot">{_e(s['footer'])}</p>
</div></body></html>"""


def plan_notes(result: PlanResult, lang: str = "id") -> list[str]:
    """Methodology caveats attached to every plan and to this report.

    Lives here rather than in api.py so the report and the API cannot drift
    into telling a reader two different stories about the same numbers.
    """
    label = 0 if norm_lang(lang) == "id" else 1
    notes = [t(lang, "note.compliance_method",
               fraction=f"{MBG.akg_fraction * 100:.0f}%"),
             t(lang, "note.method"), t(lang, "note.servings"),
             t(lang, "note.prices")]
    if not result.request.enforce_micronutrients:
        notes.append(t(lang, "note.micro"))
    if result.budget_overrun_idr > 0:
        notes.append(t(lang, "note.overrun",
                       amount=f"{result.budget_overrun_idr:,.0f}"))
    if result.relaxations:
        worst = result.relaxations[0]
        notes.append(t(lang, "note.relaxed", count=len(result.relaxations),
                       nutrient=NUTRIENT_META[worst.nutrient][label],
                       day=worst.day_index + 1, share=f"{worst.share:.0%}"))
    return notes


def _notes_for(result: PlanResult, lang: str) -> list[str]:
    return plan_notes(result, lang)
